"""RF/MAC/BBP init-value tables, verbatim from the kernel headers.

Generated by scripts/chips/mt7601u/gen_initvals.py from
driver_sources/mt7601u-source-v7.2/mt7601u/initvals_phy.h and initvals.h.
Do NOT hand-edit; re-run the generator instead.
"""
from __future__ import annotations

from .constants import MT_MCU_MEMMAP_RF
# ============================================================
# bbp_normal_temp_bw20 — [SRC] initvals_phy.h
# ============================================================
bbp_normal_temp_bw20: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x12),
    ((91) & 0xFFFF, 0x07),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x17),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x06),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x12),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x17),
]

# ============================================================
# bbp_normal_temp_bw40 — [SRC] initvals_phy.h
# ============================================================
bbp_normal_temp_bw40: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x15),
    ((91) & 0xFFFF, 0x04),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x12),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x08),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x15),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x16),
]

# ============================================================
# bbp_normal_temp — [SRC] initvals_phy.h
# ============================================================
bbp_normal_temp: list[tuple[int, int]] = [
    ((75) & 0xFFFF, 0x60),
    ((92) & 0xFFFF, 0x02),
    ((178) & 0xFFFF, 0xff),
    ((195) & 0xFFFF, 0x88),
    ((196) & 0xFFFF, 0x60),
]

# ============================================================
# bbp_high_temp_bw20 — [SRC] initvals_phy.h
# ============================================================
bbp_high_temp_bw20: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x12),
    ((91) & 0xFFFF, 0x07),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x17),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x06),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x12),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x17),
]

# ============================================================
# bbp_high_temp_bw40 — [SRC] initvals_phy.h
# ============================================================
bbp_high_temp_bw40: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x15),
    ((91) & 0xFFFF, 0x04),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x12),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x08),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x15),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x16),
]

# ============================================================
# bbp_high_temp — [SRC] initvals_phy.h
# ============================================================
bbp_high_temp: list[tuple[int, int]] = [
    ((75) & 0xFFFF, 0x60),
    ((92) & 0xFFFF, 0x02),
    ((178) & 0xFFFF, 0xff),
    ((195) & 0xFFFF, 0x88),
    ((196) & 0xFFFF, 0x60),
]

# ============================================================
# bbp_low_temp_bw20 — [SRC] initvals_phy.h
# ============================================================
bbp_low_temp_bw20: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x12),
    ((75) & 0xFFFF, 0x5e),
    ((91) & 0xFFFF, 0x07),
    ((92) & 0xFFFF, 0x02),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x17),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x06),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x12),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x17),
    ((195) & 0xFFFF, 0x88),
    ((196) & 0xFFFF, 0x5e),
]

# ============================================================
# bbp_low_temp_bw40 — [SRC] initvals_phy.h
# ============================================================
bbp_low_temp_bw40: list[tuple[int, int]] = [
    ((69) & 0xFFFF, 0x15),
    ((75) & 0xFFFF, 0x5c),
    ((91) & 0xFFFF, 0x04),
    ((92) & 0xFFFF, 0x03),
    ((195) & 0xFFFF, 0x23),
    ((196) & 0xFFFF, 0x10),
    ((195) & 0xFFFF, 0x24),
    ((196) & 0xFFFF, 0x08),
    ((195) & 0xFFFF, 0x81),
    ((196) & 0xFFFF, 0x15),
    ((195) & 0xFFFF, 0x83),
    ((196) & 0xFFFF, 0x16),
    ((195) & 0xFFFF, 0x88),
    ((196) & 0xFFFF, 0x5b),
]

# ============================================================
# bbp_low_temp — [SRC] initvals_phy.h
# ============================================================
bbp_low_temp: list[tuple[int, int]] = [
    ((178) & 0xFFFF, 0xff),
]

# ============================================================
# bbp_mode_table — [SRC] initvals_phy.h, indexed [temp_mode][bw]
# ============================================================
bbp_mode_table: list[list[list[tuple[int, int]]]] = [
    [
        bbp_normal_temp_bw20,
        bbp_normal_temp_bw40,
        bbp_normal_temp,
    ],
    [
        bbp_high_temp_bw20,
        bbp_high_temp_bw40,
        bbp_high_temp,
    ],
    [
        bbp_low_temp_bw20,
        bbp_low_temp_bw40,
        bbp_low_temp,
    ],
]

# ============================================================
# rf_central — [SRC] initvals_phy.h
# ============================================================
rf_central: list[tuple[int, int]] = [
    (MT_MCU_MEMMAP_RF | (0) << 16 | (0), 0x02),       # Bank 0 - for central blocks: BG, PLL, XTAL, LO, ADC/DAC
    (MT_MCU_MEMMAP_RF | (0) << 16 | (1), 0x01),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (2), 0x11),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (3), 0xff),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (4), 0x0a),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (5), 0x20),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (6), 0x00),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (7), 0x00),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (8), 0x00),       # B/G
    (MT_MCU_MEMMAP_RF | (0) << 16 | (9), 0x00),     
    (MT_MCU_MEMMAP_RF | (0) << 16 | (10), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (11), 0x21),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (13), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (14), 0x7c),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (15), 0x22),      # XO
    (MT_MCU_MEMMAP_RF | (0) << 16 | (16), 0x80),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (17), 0x99),      # RF_REG_PAIR(0,	13, 0x13), 	 20mhz xtal
    (MT_MCU_MEMMAP_RF | (0) << 16 | (18), 0x99),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (19), 0x09),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (20), 0x50),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (21), 0xb0),      # PLL
    (MT_MCU_MEMMAP_RF | (0) << 16 | (22), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (23), 0xc5),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (24), 0xfc),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (25), 0x40),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (26), 0x4d),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (27), 0x02),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (28), 0x72),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (29), 0x01),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (30), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (31), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (32), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (33), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (34), 0x23),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (35), 0x01),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (36), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (37), 0x00),      # test ports
    (MT_MCU_MEMMAP_RF | (0) << 16 | (38), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (39), 0x20),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (40), 0x00),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (41), 0xd0),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (42), 0x1b),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (43), 0x02),    
    (MT_MCU_MEMMAP_RF | (0) << 16 | (44), 0x00),      # ADC/DAC
]

# ============================================================
# rf_channel — [SRC] initvals_phy.h
# ============================================================
rf_channel: list[tuple[int, int]] = [
    (MT_MCU_MEMMAP_RF | (4) << 16 | (0), 0x01),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (1), 0x00),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (2), 0x00),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (3), 0x00),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (4), 0x00),       # LDO
    (MT_MCU_MEMMAP_RF | (4) << 16 | (5), 0x08),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (6), 0x00),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (7), 0x5b),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (8), 0x52),       # RX
    (MT_MCU_MEMMAP_RF | (4) << 16 | (9), 0xb6),     
    (MT_MCU_MEMMAP_RF | (4) << 16 | (10), 0x57),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (11), 0x33),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (12), 0x22),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (13), 0x3d),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (14), 0x3e),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (15), 0x13),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (16), 0x22),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (17), 0x23),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (18), 0x02),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (19), 0xa4),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (20), 0x01),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (21), 0x12),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (22), 0x80),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (23), 0xb3),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (24), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (25), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (26), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (27), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (28), 0x18),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (29), 0xee),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (30), 0x6b),      # LOGEN
    (MT_MCU_MEMMAP_RF | (4) << 16 | (31), 0x31),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (32), 0x5d),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (33), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (34), 0x96),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (35), 0x55),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (36), 0x08),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (37), 0xbb),      # TX
    (MT_MCU_MEMMAP_RF | (4) << 16 | (38), 0xb3),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (39), 0xb3),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (40), 0x03),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (41), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (42), 0x00),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (43), 0xc5),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (44), 0xc5),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (45), 0xc5),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (46), 0x07),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (47), 0xa8),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (48), 0xef),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (49), 0x1a),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (54), 0x07),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (55), 0xa7),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (56), 0xcc),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (57), 0x14),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (58), 0x07),      # PA
    (MT_MCU_MEMMAP_RF | (4) << 16 | (59), 0xa8),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (60), 0xd7),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (61), 0x10),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (62), 0x1c),    
    (MT_MCU_MEMMAP_RF | (4) << 16 | (63), 0x00),    
]

# ============================================================
# rf_vga — [SRC] initvals_phy.h
# ============================================================
rf_vga: list[tuple[int, int]] = [
    (MT_MCU_MEMMAP_RF | (5) << 16 | (0), 0x47),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (1), 0x00),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (2), 0x00),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (3), 0x08),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (4), 0x04),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (5), 0x20),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (6), 0x3a),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (7), 0x3a),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (8), 0x00),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (9), 0x00),     
    (MT_MCU_MEMMAP_RF | (5) << 16 | (10), 0x10),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (11), 0x10),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (12), 0x10),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (13), 0x10),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (14), 0x10),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (15), 0x20),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (16), 0x22),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (17), 0x7c),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (18), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (19), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (20), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (21), 0xf1),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (22), 0x11),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (23), 0x02),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (24), 0x41),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (25), 0x20),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (26), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (27), 0xd7),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (28), 0xa2),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (29), 0x20),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (30), 0x49),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (31), 0x20),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (32), 0x04),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (33), 0xf1),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (34), 0xa1),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (35), 0x01),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (41), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (42), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (43), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (44), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (45), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (46), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (47), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (48), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (49), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (50), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (51), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (52), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (53), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (54), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (55), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (56), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (57), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (58), 0x31),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (59), 0x31),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (60), 0x0a),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (61), 0x02),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (62), 0x00),    
    (MT_MCU_MEMMAP_RF | (5) << 16 | (63), 0x00),    
]

