"""Generate the MT7601U init-value tables from the v7.2 headers, verbatim.

RF_REG_PAIR(bank, reg, value) expands to { MT_MCU_MEMMAP_RF | bank << 16 | reg, value }
(initvals_phy.h:10). Values are copied straight out of the C, never retyped, and
each table keeps its source comment structure so a reviewer can diff it.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "driver_sources" / "mt7601u-source-v7.2" / "mt7601u"

RF_PAIR = re.compile(r"RF_REG_PAIR\(\s*(\w+|\d+)\s*,\s*(\w+|\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\)")


def parse_table(text: str, name: str) -> list[tuple[str, list[tuple[str, str, str]], list[str]]]:
    """One (table_name, entries, interleaved_comment_lines) triple."""
    start = text.index(f"{name}[] = {{")
    end = text.index("};", start)
    body = text[start + len(f"{name}[] = {{"):end]

    entries: list[tuple[str, str, str]] = []
    comments: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("/*") or stripped.startswith("*") or stripped.startswith("//"):
            comments.append(stripped)
            continue
        m = RF_PAIR.search(stripped)
        if m:
            entries.append(m.groups())
            comments.append("")
    return name, entries, comments


def emit(out: list[str], name: str, entries, comments, base_expr: str) -> None:
    out.append(f"{name}: list[tuple[int, int]] = [")
    for (bank, reg, value), comment in zip(entries, comments):
        c = comment.replace("*/", "").replace("/*", "").strip()
        c = re.sub(r"^\*+\s*", "", c).strip()
        addr = f"{base_expr} | ({bank}) << 16 | ({reg})"
        tail = f"  # {c}" if c else ""
        out.append(f"    ({addr}, {value}),".ljust(52) + tail)
    out.append("]")
    out.append("")


def main() -> None:
    phy = (SRC / "initvals_phy.h").read_text()

    out: list[str] = []
    out.append('"""RF/MAC/BBP init-value tables, verbatim from the kernel headers.')
    out.append("")
    out.append("Generated by scripts/chips/mt7601u/gen_initvals.py from")
    out.append("driver_sources/mt7601u-source-v7.2/mt7601u/initvals_phy.h and initvals.h.")
    out.append("Do NOT hand-edit; re-run the generator instead.")
    out.append('"""')
    out.append("from __future__ import annotations")
    out.append("")
    # The temperature-mode tables: flat { reg, value } lists chained in one C
    # declarator, indexed by bbp_mode_table as [temp_mode][bw] where bw 0 is 20 MHz,
    # 1 is 40 MHz and 2 is the common (width-independent) set.
    for mode, prefix in (("NORMAL", "bbp_normal_temp"),
                         ("HIGH", "bbp_high_temp"),
                         ("LOW", "bbp_low_temp")):
        for bw, suffix in ((0, "_bw20"), (1, "_bw40"), (2, "")):
            name = prefix + suffix
            entries = parse_plain_table(phy, name)
            listed = _strip_comments(table_body(phy, name)).count("{")
            if len(entries) != listed:
                raise SystemExit(f"{name}: parsed {len(entries)} of {listed} entries")
            out.append(f"# {'=' * 60}")
            out.append(f"# {name} — [SRC] initvals_phy.h")
            out.append(f"# {'=' * 60}")
            out.append(f"{name}: list[tuple[int, int]] = [")
            for reg, value in entries:
                out.append(f"    (({reg}) & 0xFFFF, {value}),")
            out.append("]")
            out.append("")

    out.append("# ============================================================")
    out.append("# bbp_mode_table — [SRC] initvals_phy.h, indexed [temp_mode][bw]")
    out.append("# ============================================================")
    out.append("bbp_mode_table: list[list[list[tuple[int, int]]]] = [")
    for prefix in ("bbp_normal_temp", "bbp_high_temp", "bbp_low_temp"):
        out.append("    [")
        for suffix in ("_bw20", "_bw40", ""):
            out.append(f"        {prefix}{suffix},")
        out.append("    ],")
    out.append("]")
    out.append("")

    for name in ("rf_central", "rf_channel", "rf_vga"):
        _n, entries, comments = parse_table(phy, name)
        out.append(f"# {'=' * 60}")
        out.append(f"# {name} — [SRC] initvals_phy.h")
        out.append(f"# {'=' * 60}")
        emit(out, name, entries, comments, "MT_MCU_MEMMAP_RF")

    out.insert(8, "from .constants import MT_MCU_MEMMAP_RF")

    target = REPO / "src" / "wifit3" / "chips" / "mt7601u" / "initvals_phy.py"
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target}")
    # The temperature-mode tables: flat { reg, value } lists chained in one C
    # declarator, indexed by bbp_mode_table as [temp_mode][bw] where bw 0 is 20 MHz,
    # 1 is 40 MHz and 2 is the common (width-independent) set.
    for mode, prefix in (("NORMAL", "bbp_normal_temp"),
                         ("HIGH", "bbp_high_temp"),
                         ("LOW", "bbp_low_temp")):
        for bw, suffix in ((0, "_bw20"), (1, "_bw40"), (2, "")):
            name = prefix + suffix
            entries = parse_plain_table(phy, name)
            listed = _strip_comments(table_body(phy, name)).count("{")
            if len(entries) != listed:
                raise SystemExit(f"{name}: parsed {len(entries)} of {listed} entries")
            out.append(f"# {'=' * 60}")
            out.append(f"# {name} — [SRC] initvals_phy.h")
            out.append(f"# {'=' * 60}")
            out.append(f"{name}: list[tuple[int, int]] = [")
            for reg, value in entries:
                out.append(f"    (({reg}) & 0xFFFF, {value}),")
            out.append("]")
            out.append("")

    out.append("# ============================================================")
    out.append("# bbp_mode_table — [SRC] initvals_phy.h, indexed [temp_mode][bw]")
    out.append("# ============================================================")
    out.append("bbp_mode_table: list[list[list[tuple[int, int]]]] = [")
    for prefix in ("bbp_normal_temp", "bbp_high_temp", "bbp_low_temp"):
        out.append("    [")
        for suffix in ("_bw20", "_bw40", ""):
            out.append(f"        {prefix}{suffix},")
        out.append("    ],")
    out.append("]")
    out.append("")

    for name in ("rf_central", "rf_channel", "rf_vga"):
        _n, entries, _c = parse_table(phy, name)
        print(f"  {name}: {len(entries)} entries")

    generate_mac()


# The register token is either a bare name or an indexed macro such as
# MT_BCN_OFFSET(0); matching only a bare name silently drops every indexed entry.
COMMENT = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)


def _strip_comments(text: str) -> str:
    """Drop C comments so a brace or a value inside one cannot skew the counts."""
    return COMMENT.sub("", text)


PLAIN_PAIR = re.compile(
    r"\{\s*(\w+(?:\(\s*\d+\s*\))?|\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\}",
    re.ASCII)


def table_body(text: str, name: str) -> str:
    """The text between one table's ``= {`` and the line that closes it.

    initvals_phy.h chains several tables in one declarator
    (``..., bbp_low_temp[] = { ... }, bbp_normal_temp[] = { ... };``), so cutting
    at the first ``};`` runs into the next table. A line-initial ``}`` ends this one.
    """
    start = text.index(f"{name}[] = {{")
    body_start = start + len(f"{name}[] = {{")
    end = re.search(r"^\}", text[body_start:], re.M)
    if end is None:
        raise SystemExit(f"{name}: no closing brace found")
    return text[body_start:body_start + end.start()]


def parse_plain_table(text: str, name: str) -> list[tuple[str, str]]:
    """One initvals.h table: plain ``{ reg, value }`` entries, no address macro."""
    return PLAIN_PAIR.findall(_strip_comments(table_body(text, name)))


def generate_mac() -> None:
    """The WLAN and BBP register tables from initvals.h, into initvals_mac.py."""
    text = (SRC / "initvals.h").read_text()
    tables = (("mac_common_vals", "MT_MCU_MEMMAP_WLAN"),
              ("mac_chip_vals", "MT_MCU_MEMMAP_WLAN"),
              ("bbp_common_vals", "MT_MCU_MEMMAP_BBP"),
              ("bbp_chip_vals", "MT_MCU_MEMMAP_BBP"))

    body: list[str] = []
    entries_src: list[str] = []
    for name, base in tables:
        entries = parse_plain_table(text, name)
        listed = _strip_comments(table_body(text, name)).count("{")
        if len(entries) != listed:
            raise SystemExit(f"{name}: parsed {len(entries)} of {listed} entries -- "
                             "an entry form the regex does not match")
        body += [f"# {'=' * 60}",
                 f"# {name} — [SRC] initvals.h, {base}",
                 f"# {'=' * 60}",
                 f"{name}: list[tuple[int, int]] = ["]
        # initvals.h stores BARE offsets: mt7601u_write_reg_pairs adds the base
        # itself (mcu.c). Unlike RF_REG_PAIR in initvals_phy.h, nothing here is
        # pre-based, so emitting the base here would double it onto the wire.
        body += [f"    (({reg}) & 0xFFFF, {value})," for reg, value in entries]
        entries_src += [reg for reg, _v in entries]
        body += ["]", ""]

    # Import exactly the register names the tables reference, so a missing constant
    # fails at import time rather than silently producing a wrong address.
    # Scan the entries only: the header comments mention the base for the reader,
    # which would otherwise pull in an import nothing references.
    names = sorted(set(re.findall(r"\bMT_[A-Z0-9_]+\b", "\n".join(entries_src))))

    out = ['"""WLAN and BBP init-value tables, verbatim from the kernel headers.',
           "",
           "Generated by scripts/chips/mt7601u/gen_initvals.py from",
           "driver_sources/mt7601u-source-v7.2/mt7601u/initvals.h.",
           "Do NOT hand-edit; re-run the generator instead.",
           '"""',
           "from __future__ import annotations",
           "",
           "from .constants import ("]
    out += [f"    {n}," for n in names]
    out += [")", ""] + body

    target = REPO / "src" / "wifit3" / "chips" / "mt7601u" / "initvals_mac.py"
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target}")
    for name, _base in tables:
        print(f"  {name}: {len(parse_plain_table(text, name))} entries")


if __name__ == "__main__":
    main()
